TOP=../..
include $(TOP)/configure/CONFIG
DB += testAsynPortDriver.db
DB += AxiVersion.db
DB += PrbsTx.db
DB += AxiXadc.db
DB += AxiAd5780.db
DB += TenGigEthReg.db
DB += JesdRx.db
DB += JesdTx.db
DB += Lmk04828.db
DB += Adc16Dx370.db
DB += AxiAd5780.db
DB += Dac38J84.db
DB += Pgp2bAxi.db
DB += AmcGenericAdcDacCtrl.db
DB += JesdRxDaq.db
include $(TOP)/configure/RULES
