d = { 'name': "AmcGenericAdcDacCtrl",
     'addrSize' : "4",
     'registers': [
                   {'name'    : "AdcValid0",
                    'address' : "0x00",
                    'type'    : "Status" },
                   {'name'    : "AdcValid1",
                    'address' : "0x01",
                    'type'    : "Status" },
                   {'name'    : "AdcValid2",
                    'address' : "0x02",
                    'type'    : "Status" },
                   {'name'    : "AdcValid3",
                    'address' : "0x03",
                    'type'    : "Status" },
                   {'name'    : "StatusReg",
                    'address' : "0x3F",
                    'size'    : "4",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   { 'name'   : "Adc0_t0",
                    'address' : "0x40",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc0_t1",
                    'address' : "0x41",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc0_t2",
                    'address' : "0x42",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc0_t3",
                    'address' : "0x43",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc1_t0",
                    'address' : "0x44",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc1_t1",
                    'address' : "0x45",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc1_t2",
                    'address' : "0x46",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc1_t3",
                    'address' : "0x47",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc2_t0",
                    'address' : "0x48",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc2_t1",
                    'address' : "0x49",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc2_t2",
                    'address' : "0x4A",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc2_t3",
                    'address' : "0x4B",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc3_t0",
                    'address' : "0x4C",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc3_t1",
                    'address' : "0x4D",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc3_t2",
                    'address' : "0x4E",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Adc3_t3",
                    'address' : "0x4F",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac0_t0",
                    'address' : "0x50",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac0_t1",
                    'address' : "0x51",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac0_t2",
                    'address' : "0x52",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac0_t3",
                    'address' : "0x53",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac1_t0",
                    'address' : "0x54",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac1_t1",
                    'address' : "0x55",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac1_t2",
                    'address' : "0x56",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Dac1_t3",
                    'address' : "0x57",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "DacVco",
                    'address' : "0x7E",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "AmcClkFreq",
                    'address' : "0x7F",
                    'type'    : "Status" },
                   {'name'    : "LmkClkSel",
                    'address' : "0x80",
                    'size'    : "2",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "LmkRst",
                    'address' : "0x81",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "lmkSync",
                    'address' : "0x82",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "LmkStatus",
                    'address' : "0x83",
                    'size'    : "2",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "loopback",
                    'address' : "0x84",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "CounterReset",
                    'address' : "0xFF",
                    'type'    : "Configuration" }
 ]
}
