d = { 'name': "AxiAd5780",
     'registers': [{ 'name'   : "dacRefreshRate",
                    'address' : "0x10",
                    'type'    : "Status" },
                   {'name'    : "dacData",
                    'address' : "0x30",
                    'type'    : "Status" },
                   {'name'    : "debugMux",
                    'address' : "0x80",
                    'type'    : "Configuration" },
                   {'name'    : "debugData",
                    'address' : "0x90",
                    'type'    : "Configuration" },
                   {'name'    : "sdoDisable",
                    'address' : "0xA0",
                    'type'    : "Configuration" },
                   {'name'    : "binaryOffset",
                    'address' : "0xA1",
                    'type'    : "Configuration" },
                   {'name'    : "dacTriState",
                    'address' : "0xA2",
                    'type'    : "Configuration" },
                   {'name'    : "opGnd",
                    'address' : "0xA3",
                    'type'    : "Conifiguration" },
                   {'name'    : "rbuf",
                    'address' : "0xA4",
                    'type'    : "Configuration" },
                   {'name'    : "halfSckPeriod",
                    'address' : "0xA5",
                    'type'    : "Status" },
                   {'name'    : "dacRst",
                    'address' : "0xFE",
                    'type'    : "Configuration" } ],
     'commands': [{ 'name'   : "dacRst"} ]
   }
