d = { 'name': "AxiVersion",
     'registers': [{ 'name'   : "FpgaVersion",
                    'address' : "0x00",
                    'type'    : "Status" },
                   {'name'    : "ScratchPad",
                    'address' : "0x01",
                    'type'    : "Configuration" },
                   {'name'    : "DeviceDnaHigh",
                    'address' : "0x02",
                    'type'    : "Status" },
                   {'name'    : "DeviceDnaLow",
                    'address' : "0x03",
                    'type'    : "Status" },
                   {'name'    : "FdSerialHigh",
                    'address' : "0x04",
                    'type'    : "Status" },
                   {'name'    : "FdSerialLow",
                    'address' : "0x05",
                    'type'    : "Status" },
                   {'name'    : "MasterReset",
                    'address' : "0x06",
                    'type'    : "Configuration" },
                   {'name'    : "FpgaReload",
                    'address' : "0x07",
                    'type'    : "Configuration" },
                   {'name'    : "FpgaReloadAddress",
                    'address' : "0x08",
                    'type'    : "Configuration" },
                   {'name'    : "Counter",
                    'address' : "0x09",
                    'type'    : "Status" },
                   {'name'    : "FpgaReloadHalt",
                    'address' : "0x0A",
                    'type'    : "Configuration" },
                   {'name'    : "UserConstants",
                    'address' : "0x100",
                    'nelms'   : "64",
                    'type'    : "Status" },
                   {'name'    : "BuildStamp",
                    'address' : "0x200",
                    'size'    : "8",
                    'nelms'   : "64",
                    'dtype'   : "string",
                    'type'    : "Status" } ],
     'commands': [{ 'name'   : "MasterReset"},
                  { 'name'   : "FpgaReload"},
                  { 'name'   : "CounterReset"} ]
   }
