d = { 'name': "CentralNode",
     'registers': [{ 'name'   : "CounterReset",
                    'address' : "0x00",
                    'type'    : "Configuration" },
                   {'name'    : "MsgErrCounter",
                    'address' : "0x01",
                    'type'    : "Status" },
                   {'name'    : "MsgOverflowCounter",
                    'address' : "0x02",
                    'type'    : "Status" },
                   {'name'    : "DigitalInputMask0",
                    'address' : "0x40",
                    'type'    : "Configuration" },
                   {'name'    : "DigitalInputMask1",
                    'address' : "0x41",
                    'type'    : "Configuration" },
                   {'name'    : "DigitalInputMask2",
                    'address' : "0x42",
                    'type'    : "Configuration" },
                   {'name'    : "ForceMitMsgEn",
                    'address' : "0x44",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "ForceMitMsgVal",
                    'address' : "0x45",
                    'size'    : "8",
                    'lsBit'   : "0",
                    'type'    : "Configuration" },
                   {'name'    : "DigitalInputState0",
                    'address' : "0x80",
                    'type'    : "Status" },
                   {'name'    : "DigitalInputState1",
                    'address' : "0x81",
                    'type'    : "Status" },
                   {'name'    : "DigitalInputState2",
                    'address' : "0x82",
                   'type'    : "Status" }],
     'commands': [{ 'name'   : "CounterReset"} ] 
   }
