d = { 'name': "Dac38J84",
     'registers': [{ 'name'   : "IntStatus",
                    'address' : "0x07",
                    'type'    : "Status" },
                  { 'name'   : "LaneBufferDelay",
                    'size'   : "5",
                    'lsBit'  : "0",
                    'address' : "0x07",
                    'type'    : "Status" },
                  { 'name'   : "Temperature",
                    'size'   : "8",
                    'lsBit'  : "8",
                    'address' : "0x07",
                    'type'    : "Status" },
                   {'name'    : "L1ErrCnt",
                    'address' : "0x41",
                    'type'    : "Status" },
                   {'name'    : "L2ErrCnt",
                    'address' : "0x42",
                    'type'    : "Status" },
                   {'name'    : "L1SERDES_alarm",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1ReadFifoEmpty",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1ReadFifoUnderflow",
                    'size'    : "1",
                    'lsBit'   : "1",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1ReadFifoFull",
                    'size'    : "1",
                    'lsBit'   : "2",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1ReadFifoOverflow",
                    'size'    : "1",
                    'lsBit'   : "3",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1DispErr",
                    'size'    : "1",
                    'lsBit'   : "8",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1NotitableErr",
                    'size'    : "1",
                    'lsBit'   : "9",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1CodeSyncErr",
                    'size'    : "1",
                    'lsBit'   : "10",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1FirstDataMatchErr",
                    'size'    : "1",
                    'lsBit'   : "11",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1ElasticBuffOverflow",
                    'size'    : "1",
                    'lsBit'   : "12",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1LinkConfigErr",
                    'size'    : "1",
                    'lsBit'   : "13",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1FrameAlignErr",
                    'size'    : "1",
                    'lsBit'   : "14",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L1MultiFrameAlignErr",
                    'size'    : "1",
                    'lsBit'   : "15",
                    'address' : "0x64",
                    'type'    : "Status" },
                   {'name'    : "L2SERDES_alarm",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2ReadFifoEmpty",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2ReadFifoUnderflow",
                    'size'    : "1",
                    'lsBit'   : "1",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2ReadFifoFull",
                    'size'    : "1",
                    'lsBit'   : "2",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2ReadFifoOverflow",
                    'size'    : "1",
                    'lsBit'   : "3",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2DispErr",
                    'size'    : "1",
                    'lsBit'   : "8",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2NotitableErr",
                    'size'    : "1",
                    'lsBit'   : "9",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2CodeSyncErr",
                    'size'    : "1",
                    'lsBit'   : "10",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2FirstDataMatchErr",
                    'size'    : "1",
                    'lsBit'   : "11",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2ElasticBuffOverflow",
                    'size'    : "1",
                    'lsBit'   : "12",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2LinkConfigErr",
                    'size'    : "1",
                    'lsBit'   : "13",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2FrameAlignErr",
                    'size'    : "1",
                    'lsBit'   : "14",
                    'address' : "0x65",
                    'type'    : "Status" },
                   {'name'    : "L2MultiFrameAlignErr",
                    'size'    : "1",
                    'lsBit'   : "15",
                    'address' : "0x65",
                    'type'    : "Status"},
                   {'name'    : "L3SERDES_alarm",
                    'address' : "0x66",
                    'type'    : "Status"},
                   {'name'    : "L4SERDES_alarm",
                    'address' : "0x67",
                    'type'    : "Status"},
                   {'name'    : "L5SERDES_alarm",
                    'address' : "0x68",
                    'type'    : "Status"},
                   {'name'    : "L6SERDES_alarm",
                    'address' : "0x69",
                    'type'    : "Status"},
                   {'name'    : "L7SERDES_alarm",
                    'address' : "0x6A",
                    'type'    : "Status"},
                   {'name'    : "L8SERDES_alarm",
                    'address' : "0x6B",
                    'type'    : "Status"},
                   {'name'    : "Sysref_alarm",
                    'address' : "0x6C",
                    'type'    : "Status"},
                   {'name'    : "Serdes1pllAlarm",
                    'size'    : "1",
                    'lsBit'   : "2",
                    'address' : "0x6C",
                    'type'    : "Status"},
                   {'name'    : "Serdes0pllAlarm",
                    'size'    : "1",
                    'lsBit'   : "3",
                    'address' : "0x6C",
                    'type'    : "Status"},
                   {'name'    : "SysRefAlarms",
                    'size'    : "4",
                    'lsBit'   : "12",
                    'address' : "0x6C",
                    'type'    : "Status"},
                   {'name'    : "Lane_alarm",
                    'address' : "0x6D",
                    'type'    : "Status"},
                   {'name'    : "Lane1Loss",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'address' : "0x6D",
                    'type'    : "Status"},
                   {'name'    : "Lane2Loss",
                    'size'    : "1",
                    'lsBit'   : "1",
                    'address' : "0x6D",
                    'type'    : "Status"},
                   {'name'    : "Lane1Alarm",
                    'size'    : "1",
                    'lsBit'   : "8",
                    'address' : "0x6D",
                    'type'    : "Status"},
                   {'name'    : "Lane2Alarm",
                    'size'    : "1",
                    'lsBit'   : "9",
                    'address' : "0x6D",
                    'type'    : "Status"},
                   {'name'    : "IDs",
                    'address' : "0x7F",
                    'type'    : "Status"}],
     'commands': [{ 'name'   : "ClearDACAlarms"},
                  { 'name'   : "InitDAC_JESD"} ]
}


for i in range(0x0, 0x7):
	if (i == 0x07):
		pass
	elif (i>= 0x1C and i<= 0x1D):
		pass
	elif (i>= 0x27 and i<= 0x2C):
		pass
	elif (i >= 0x35 and i<=0x3A):
		pass
	elif(i >= 0x40 and i<=0x42):
		pass
	elif(i == 0x53):
		pass
	elif(i == 0x56):
		pass
	elif(i == 0x59):
		pass
	elif(i == 0x5D):
		pass
	elif(i == 0x5E):
		pass
	elif(i >= 0x62 and i<=0x63):
		pass
	elif(i >= 0x64 and i<=0x6D):
		pass
	elif(i == 0x7E):
		pass
	elif(i == 0x7F):
		pass
	else:
		nme = "DacReg"
		addr = "{0:#0{1}x}".format(i,6)
		nme += str(addr)
		d['registers'].append(
                   {'name'    : nme,
                    'address' : addr,
                    'type'    : "Configuration" } )
