d = { 'name': "JesdRxDaq",
     'registers': [{ 'name'   : "SwDaqTrigger",
                    'address' : "0x00",
                    'type'    : "Configuration" },
                   {'name'    : "SwDaqTrigger0",
                    'size'    : "0",
                    'lsBit'   : "0",
                    'address' : "0x00",
                    'type'    : "Configuration" },
                   {'name'    : "SampleDecimation",
                    'address' : "0x02",
                    'type'    : "Configuration" },
                   {'name'    : "DaqBufferSize",
                    'address' : "0x03",
                    'type'    : "Configuration" },
                   {'name'    : "S1ChannelSelect",
                    'address' : "0x10",
                    'type'    : "Configuration" },
                   {'name'    : "S2ChannelSelect",
                    'address' : "0x11",
                    'type'    : "Configuration" },
                   {'name'    : "StatusStream0",
                    'address' : "0x20",
                    'type'    : "Status" },
                   {'name'    : "Pause0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Idle0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "1",
                    'type'    : "Status" },
                   {'name'    : "Overflow0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "2",
                    'type'    : "Status" },
                   {'name'    : "Error0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "3",
                    'type'    : "Status" },
                   {'name'    : "JESDValid0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "4",
                    'type'    : "Status" },
                   {'name'    : "Enable0",
                    'address' : "0x20",
                    'size'    : "1",
                    'lsBit'   : "5",
                    'type'    : "Status" },
                   {'name'    : "PacketCnt0",
                    'address' : "0x20",
                    'size'    : "16",
                    'lsBit'   : "16",
                    'type'    : "Status" },
                   {'name'    : "StatusStream1",
                    'address' : "0x21",
                    'type'    : "Status" },
                   {'name'    : "Pause1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "Idle1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "1",
                    'type'    : "Status" },
                   {'name'    : "Overflow1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "2",
                    'type'    : "Status" },
                   {'name'    : "Error1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "3",
                    'type'    : "Status" },
                   {'name'    : "JESDValid1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "4",
                    'type'    : "Status" },
                   {'name'    : "Enable1",
                    'address' : "0x21",
                    'size'    : "1",
                    'lsBit'   : "5",
                    'type'    : "Status" },
                   {'name'    : "PacketCnt1",
                    'address' : "0x21",
                    'size'    : "16",
                    'lsBit'   : "16",
                    'type'    : "Status" }],
     'commands': [{ 'name'   : "TriggerDAQ"}]
   }
