d = { 'name': "PrbsTx",
     'registers': [{ 'name'   : "ConfigStatus",
                    'address' : "0x00",
                    'type'    : "Configuration" },
                   { 'name'   : "AxiEn",
                     'address': "0x00",
                     'size'   : "1",
                     'lsBit'  : "0",
                     'type'   : "Configuration"},
                   { 'name'   : "TxEn",
                     'address': "0x00",
                     'size'   : "1",
                     'lsBit'  : "1",
                     'type'   : "Configuration"},
                   { 'name'   : "Busy",
                     'address': "0x00",
                     'size'   : "1",
                     'lsBit'  : "2",
                     'type'   : "Status"},
                   { 'name'   : "Overflow",
                     'address': "0x00",
                     'size'   : "1",
                     'lsBit'  : "3",
                     'type'   : "Status"},
                   {'name'    : "PacketLength",
                    'address' : "0x01",
                    'type'    : "Configuration" },
                   {'name'    : "AxiStreamCfg",
                    'address' : "0x02",
                    'type'    : "Configuration" },
                   { 'name'   : "tDest",
                     'address': "0x02",
                     'size'   : "8",
                     'lsBit'  : "0",
                     'type'   : "Configuration"},
                   { 'name'   : "tId",
                     'address': "0x02",
                     'size'   : "8",
                     'lsBit'  : "8",
                     'type'   : "Configuration"},
                   {'name'    : "DataCount",
                    'address' : "0x03",
                    'type'    : "Status" },
                   {'name'    : "EventCount",
                    'address' : "0x04",
                    'type'    : "Status" },
                   {'name'    : "RandomData",
                    'address' : "0x05",
                    'type'    : "Status" } ],
     'commands': [{ 'name'   : "OneShot"} ]
   }
