d = { 'name': "RingBuffer",
     'registers': [{ 'name'   : "WaveformSize",
                    'address' : "0x00",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'type'    : "Status" },
                   {'name'    : "RAM_ADDR_WIDTH_G",
                    'address' : "0x00",
                    'size'    : "8",
                    'lsBit'   : "20",
                    'type'    : "Status" },
                   {'name'    : "ExtdataLogClr",
                    'address' : "0x00",
                    'size'    : "1",
                    'lsBit'   : "28",
                    'type'    : "Status" },
                   {'name'    : "ExtDataLogEn",
                    'address' : "0x00",
                    'size'    : "1",
                    'lsBit'   : "29",
                    'type'    : "Status" },
                   {'name'    : "IntdataLogClr",
                    'address' : "0x00",
                    'size'    : "1",
                    'lsBit'   : "30",
                    'type'    : "Configuration" },
                   {'name'    : "IntDataLogEn",
                    'address' : "0x00",
                    'size'    : "1",
                    'lsBit'   : "31",
                    'type'    : "Configuration" },
                   {'name'    : "Reg0x0000",
                    'address' : "0x00",
                    'type'    : "Status"},
                   {'name'    : "RingBuffer",
                    'address' : "0x01",
                    'size'    : "16",
                    'lsBit'   : "0",
                    'nelms'   : "2046",
                    'type'    : "Status" } ]
   }
