TOP = ..
include $(TOP)/configure/CONFIG
#framework, builder
DIRS += deviceLibrarySrc
#cpsw asyn driver
DIRS += src
DIRS += deviceDriversSrc
#specific devices
DIRS += Kc705TenGigEthSrc
DIRS += Kcu105NoRssiSrc
DIRS += AmcCarrierSrc
DIRS += Db
include $(TOP)/configure/RULES_DIRS
