TOP = ..
include $(TOP)/configure/CONFIG
DIRS += frameworkSrc
DIRS += deviceLibrarySrc
DIRS += Kc705TenGigEthSrc
DIRS += src
DIRS += AxiVersionSrc
AxiVersionSrc_DEPEND_DIRS += src

DIRS += AxiXadcSrc
AxiXadcSrc_DEPEND_DIRS += src

DIRS += appSrc

DIRS += Db
include $(TOP)/configure/RULES_DIRS
